config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resource :ingredient_order_items, only: [:create, :update, :destroy]
  root to: "products#index"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
end

app/models/ingredient_order_item.rb
class IngredientOrderItem < ActiveRecord::Base
  belongs_to :order_item
  belongs_to :ingredient
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  before_save :update_price

  def price
    order_items.collect {|oi| oi.valid? ? oi.total_price : 0}.sum
  end

  private
  def update_price
    self[:price] = price
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  has_many :ingredient_order_items, :dependent => :delete_all
  has_many :ingredients, through: :ingredient_order_items

  accepts_nested_attributes_for :ingredient_order_items

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    (unit_price + ingredients_price) * quantity
  end

  def ingredients_price
    ingredient_order_items.reduce(0) do |sum, i|
      sum + i.ingredient.price * i.quantity
    end
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @ingredients = Ingredient.all
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(clear_order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(clear_order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id, ingredient_order_items_attributes:
        [:quantity, :ingredient_id]
    )
  end

  def clear_order_item_params
    oi_params = order_item_params
    unless oi_params[:ingredient_order_items_attributes].nil?
      oi_params[:ingredient_order_items_attributes].each do |key, value|
        if value[:quantity].to_i == 0
          oi_params[:ingredient_order_items_attributes].delete key
        end
      end
    end
    oi_params
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @ingredients = Ingredient.all
    @order_item.ingredient_order_items.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
      <% unless order_item.ingredients.empty? %>
          <h5>
            <b>Дополнительные Ингредиенты:</b>
            <% order_item.ingredients.each do |i| %>
                <%= i.name + ", "%>
            <% end %>
          </h5>
      <% end %>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
          <h4 class="text-right">Стоимость:
            <span style="color: green" id="<%= "total_price_%p" % product.id %>">
            <%= number_to_currency order_item.total_price, locale: :ru %>
          </span>
          </h4>
          <div class="row">
            <div class="col-xs-4">
              <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
              <%= f.hidden_field :product_id, value: product.id %>
            </div>
            <div class="col-xs-8 text-right">
              <div class="btn-group">
                <%= f.submit "Update", class: "btn btn-primary" %>
                <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @order_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<% if @order_items.size == 0 %>
    <p class="text-center">
      Пока нет заказов в вашей корзине.  Пожалуйста, <%= link_to "вернитесь назад", root_path %> и выберите товар.
    </p>
<% else %>
    <% @order_items.each do |order_item| %>
        <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
    <% end %>
    <h4 class="text-right">Общая цена: <span style="color: green"><%= number_to_currency current_order.price, locale: :ru %></span></h4>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Заказов в Корзине ( #{number_to_currency current_order.price, locale: :ru} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tokyo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag 'https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css' %>
      <%= javascript_include_tag 'https://code.jquery.com/jquery-3.1.1.js' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>

  <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag 'http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css' %>
      <%= javascript_include_tag 'http://code.jquery.com/jquery-3.1.1.js' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>

  <% end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "Tokyo Shop", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>


  <script>
    $('.btn-number').click(function(e){
      e.preventDefault();

      fieldName = $(this).attr('data-field');
      type      = $(this).attr('data-type');
      product_id= $(this).attr('data-product_id');
      var input = $("#product_" + product_id + " input[name='"+fieldName+"']");
      var currentVal = parseInt(input.val());
      if (!isNaN(currentVal)) {
        if(type == 'minus') {

          if(currentVal > input.attr('min')) {
            input.val(currentVal - 1).change();
          }
          if(parseInt(input.val()) == input.attr('min')) {
            $(this).attr('disabled', true);
          }

        } else if(type == 'plus') {

          if(currentVal < input.attr('max')) {
            input.val(currentVal + 1).change();
          }
          if(parseInt(input.val()) == input.attr('max')) {
            $(this).attr('disabled', true);
          }

        }
      } else {
        input.val(0);
      }
    });
    $('.input-number').focusin(function(){
      $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function() {

      minValue =  parseInt($(this).attr('min'));
      maxValue =  parseInt($(this).attr('max'));
      valueCurrent = parseInt($(this).val());

      name = $(this).attr('name');
      if(valueCurrent >= minValue) {
        $(".btn-number[data-type='minus'][data-field='"+name+"']").removeAttr('disabled')
      } else {
        alert('Sorry, the minimum value was reached');
        $(this).val($(this).data('oldValue'));
      }
      if(valueCurrent <= maxValue) {
        $(".btn-number[data-type='plus'][data-field='"+name+"']").removeAttr('disabled')
      } else {
        alert('Sorry, the maximum value was reached');
        $(this).val($(this).data('oldValue'));
      }


    });
    $(".input-number").keydown(function (e) {
      // Allow: backspace, delete, tab, escape, enter and .
      if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
          // Allow: Ctrl+A
          (e.keyCode == 65 && e.ctrlKey === true) ||
          // Allow: home, end, left, right
          (e.keyCode >= 35 && e.keyCode <= 39)) {
        // let it happen, don't do anything
        return;
      }
      // Ensure that it is a number and stop the keypress
      if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
        e.preventDefault();
      }
    });
  </script>
</body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="col-md-5 <%= cycle('', 'col-md-offset-2') %> well" id="<%= "product_%p" % product.id %>">

  <div class="row">
    <div class="col-md-12">
      <%= image_tag product.image_path, size: "430x350"%>
      <h4><%= product.name %></small></h4>
      <h5>Цена:
        <span style="color: green" id="<%= "total_price_%p" % product.id %>">
            <%= number_to_currency product.price, locale: :ru %>
          </span>
      </h5>

      <%= form_for order_item, remote: true do |f| %>
        <div class="row">
          <div class="col-md-6">
            <h4><b>Топпинг</b></h4>
            <% @ingredients.select{|item| item.ingredient_type == "topping" }.each do |ingredient| %>

              <%= f.fields_for :ingredient_order_items, remote: true do |i| %>
                <div class="row">
                  <div class="col-md-8">
                    <h4><%= ingredient.name %></h4>
                    <h5><%= number_to_currency ingredient.price, locale: :ru %></h5>
                  </div>
                  <div class="ingredient col-md-8">
                    <div class="input-group">
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-danger btn-number" data-type="minus"
                                data-field="<%= "#{i.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                          <span class="glyphicon glyphicon-minus"></span>
                        </button>
                      </span>
                      <%= i.number_field :quantity, value: 0, class: "form-control input-number", min: 0, max: 10,
                                         type: "text", onchange: "total_price(%p);" % product.id %>
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-success btn-number" data-type="plus"
                                data-field="<%= "#{i.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                          <span class="glyphicon glyphicon-plus"></span>
                        </button>
                      </span>
                    </div>
                    <%= i.hidden_field :ingredient_id, value: ingredient.id %>
                    <%= i.hidden_field :ingredient_price, value: ingredient.price %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-6">
            <h4><b>Мясо</b></h4>
            <% @ingredients.select{|item| item.ingredient_type == "meat" }.each do |ingredient| %>

              <%= f.fields_for :ingredient_order_items, remote: true do |i| %>
                <div class="row">
                  <div class="col-md-8">
                    <h4><%= ingredient.name %></h4>
                    <h5><%= number_to_currency ingredient.price, locale: :ru %></h5>

                  </div>
                  <div class="ingredient col-md-8">
                    <div class="input-group">
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-danger btn-number" data-type="minus"
                                data-field="<%= "#{i.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                          <span class="glyphicon glyphicon-minus"></span>
                        </button>
                      </span>
                      <%= i.number_field :quantity, value: 0, class: "form-control input-number", min: 0, max: 10,
                                         type: "text", onchange: "total_price(%p);" % product.id %>
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-success btn-number" data-type="plus"
                                data-field="<%= "#{i.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                          <span class="glyphicon glyphicon-plus"></span>
                        </button>
                      </span>
                    </div>
                    <%= i.hidden_field :ingredient_id, value: ingredient.id %>
                    <%= i.hidden_field :ingredient_price, value: ingredient.price %>
                  </div>

                </div>
              <% end %>

            <% end %>
          </div>

        </div>
        <br/>
        <div class="row">
          <div class="col-md-4">
            <h4>Порция: </h4>
            <%= f.hidden_field :product_price, value: product.price, id: "product_price_%p" % product.id %>
            <div class="input-group">
              <span class="input-group-btn">
                <button type="button" class="btn btn-danger btn-number" data-type="minus"
                        data-field="<%= "#{f.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                  <span class="glyphicon glyphicon-minus"></span>
                </button>
              </span>
              <%= f.number_field :quantity, value: 1, min: 1, max: 10, class: "form-control input-number", type: "text" %>
              <span class="input-group-btn">
                <button type="button" class="btn btn-success btn-number" data-type="plus"
                        data-field="<%= "#{f.object_name}[quantity]" %>" data-product_id="<%= product.id %>">
                  <span class="glyphicon glyphicon-plus"></span>
                </button>
              </span>
            </div>
          </div>
          <div class="col-md-8">
          </div>
        </div>
        <br/>
        <div class="input-group-btn">
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.submit "Добавить в корзину", class: "btn btn-primary" %>
        </div>

      <% end %>

    </div>



  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">ТОВАРЫ</h3>

<div class="row">
  <div class="col-md-12">
    <% @products.each do |product| %>
        <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>